UPDATE prot_db.protein SET localization = 'cytoplasm', mol_weight = 41606, type = 'cytoskeletal protein', seq_id = 1, gene_loc = '4p22.7', gene = 'Act5c' WHERE name = 'actin';
UPDATE prot_db.protein SET localization = 'cytoplasm/extra', mol_weight = 52854, type = 'chaperone protein', seq_id = 2, gene_loc = '2q33.1', gene = 'Cpn60' WHERE name = 'groEL';
UPDATE prot_db.protein SET localization = 'cytoplasm/extra', mol_weight = 70954, type = 'enzyme', seq_id = 3, gene_loc = '7q22', gene = 'AChE' WHERE name = 'acetylcholinesterase';
UPDATE prot_db.protein SET localization = 'extracellular', mol_weight = 34987, type = 'hemoprotein', seq_id = 4, gene_loc = '7p45.8', gene = null WHERE name = 'hemoglobin';
UPDATE prot_db.protein SET localization = 'extracellular', mol_weight = 47987, type = 'transmembrane receptor', seq_id = 5, gene_loc = '9p32.1', gene = null WHERE name = 'nicotonic acetylcholine receptor';
UPDATE prot_db.protein SET localization = 'extracellular', mol_weight = 106789, type = 'enzyme', seq_id = 6, gene_loc = '11p11-q12', gene = null WHERE name = 'thrombin';
UPDATE prot_db.protein SET localization = 'cytoplasm/extra', mol_weight = 54302, type = 'cell adhesion', seq_id = 7, gene_loc = '4q12.4', gene = null WHERE name = 'integrin';
UPDATE prot_db.protein SET localization = 'cytoplasm/extra', mol_weight = 46383, type = 'g-protein coupled receptor', seq_id = 8, gene_loc = '20p23.9', gene = null WHERE name = 'rhodopsin';
UPDATE prot_db.protein SET localization = 'cytoplasm/extra', mol_weight = 98765, type = 'enzyme', seq_id = 9, gene_loc = '16p10.5', gene = null WHERE name = 'formaldehyde dismutase';
UPDATE prot_db.protein SET localization = 'cytoplasm/extra', mol_weight = 23457, type = 'enzyme', seq_id = 10, gene_loc = '19p15.8', gene = null WHERE name = 'Lecithin–cholesterol acyltransferase';
UPDATE prot_db.protein SET localization = 'cytoplasm/extra', mol_weight = 78654, type = 'enzyme', seq_id = 11, gene_loc = '20q16.2', gene = null WHERE name = 'ATP Synthase';
UPDATE prot_db.protein SET localization = 'cytoplasm/extra', mol_weight = 54632, type = 'enzyme', seq_id = 12, gene_loc = '6q18.7', gene = null WHERE name = 'serine racemase';