UPDATE prot_db.mutation SET type = 'muscular degnerative' WHERE disease_name = 'myopathy' AND prot_name = 'actin';
UPDATE prot_db.mutation SET type = 'nuerodegenerative' WHERE disease_name = 'mitochondrial encephalitis' AND prot_name = 'groEL';
UPDATE prot_db.mutation SET type = 'nuerodegenerative' WHERE disease_name = 'Alzheimers' AND prot_name = 'acetylcholinesterase';
UPDATE prot_db.mutation SET type = 'nuerodegenerative' WHERE disease_name = 'parkinsons' AND prot_name = 'nicotonic acetylcholine receptor';
UPDATE prot_db.mutation SET type = 'developmental disorder' WHERE disease_name = 'autism' AND prot_name = 'nicotonic acetylcholine receptor';
UPDATE prot_db.mutation SET type = 'dissociative personality' WHERE disease_name = 'schizophrenia' AND prot_name = 'nicotonic acetylcholine receptor';
UPDATE prot_db.mutation SET type = 'hypoxic disorder' WHERE disease_name = 'anemia' AND prot_name = 'hemoglobin';
UPDATE prot_db.mutation SET type = 'blood disorder' WHERE disease_name = 'prothrombin difficiency' AND prot_name = 'thrombin';
UPDATE prot_db.mutation SET type = 'null' WHERE disease_name = 'fibrosis' AND prot_name = 'integrin';
UPDATE prot_db.mutation SET type = 'blood disorder' WHERE disease_name = 'atherosclerosis' AND prot_name = 'integrin';
UPDATE prot_db.mutation SET type = 'retinal degenerative' WHERE disease_name = 'retinal degenerative disorder' AND prot_name = 'rhodopsin';